//! Self-update command implementation.
//!
//! Downloads the latest APVM release from GitHub, verifies the SHA-256
//! checksum, and atomically replaces the running binary.
//!
//! # Cross-platform binary replacement
//!
//! - **Unix (Linux / macOS):** The kernel tracks open files by inode, not path.
//!   `self-replace` places the new binary next to the current executable and
//!   performs an atomic `rename(2)`.
//!   Source: <https://man7.org/linux/man-pages/man2/rename.2.html>
//!
//! - **Windows:** A running `.exe` can be renamed but not deleted. `self-replace`
//!   renames the current binary aside, puts the new one in place, then spawns a
//!   helper process with `FILE_FLAG_DELETE_ON_CLOSE` to clean up after exit.
//!   Source: <https://docs.rs/self-replace/1/self_replace/#implementation>
//!
//! # Security
//!
//! - Binary integrity is verified with SHA-256 against the `checksums.txt`
//!   asset published alongside each release.
//! - All downloads are HTTPS-only (enforced by `reqwest` with `native-tls`).
//! - The repository owner/name is hardcoded — no user-controlled redirect.

use std::io::Write;

use sha2::{Digest, Sha256};

use apvm_core::error::{Error, Result};
use apvm_core::github::{GitHubClient, Release, ReleaseAsset};

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

/// GitHub repository owner for APVM releases.
const REPO_OWNER: &str = "wp-media";

/// GitHub repository name for APVM releases.
const REPO_NAME: &str = "automation-plugin-version-manager";

/// Name of the SHA-256 checksums file attached to each release.
///
/// Generated by the `release-cli.yml` workflow:
/// `sha256sum apvm-* > checksums.txt`
const CHECKSUMS_FILENAME: &str = "checksums.txt";

/// Current version of this binary, set at compile time.
///
/// Source: <https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates>
const CURRENT_VERSION: &str = env!("CARGO_PKG_VERSION");

// ─────────────────────────────────────────────────────────────────────────────
// ANSI color helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Green check mark for success messages.
fn success(msg: &str) {
    eprintln!("  \x1b[32m✓\x1b[0m  {msg}");
}

/// Blue info prefix.
fn info(msg: &str) {
    eprintln!("\x1b[34minfo\x1b[0m  {msg}");
}

/// Red error prefix.
fn error_msg(msg: &str) {
    eprintln!("\x1b[31merror\x1b[0m {msg}");
}

// ─────────────────────────────────────────────────────────────────────────────
// Platform detection
// ─────────────────────────────────────────────────────────────────────────────

/// Map the current platform to the release artifact name.
///
/// Artifact names must match those published by `.github/workflows/release-cli.yml`.
///
/// # Sources
///
/// - [`std::env::consts::OS`]: compile-time constant for the target OS.
///   <https://doc.rust-lang.org/std/env/consts/constant.OS.html>
/// - [`std::env::consts::ARCH`]: compile-time constant for the target architecture.
///   <https://doc.rust-lang.org/std/env/consts/constant.ARCH.html>
fn artifact_name() -> Result<&'static str> {
    match (std::env::consts::OS, std::env::consts::ARCH) {
        ("macos", "aarch64") => Ok("apvm-darwin-arm64"),
        ("macos", "x86_64") => Ok("apvm-darwin-x64"),
        ("linux", "x86_64") => Ok("apvm-linux-x64-gnu"),
        ("linux", "aarch64") => Ok("apvm-linux-arm64-gnu"),
        ("windows", "x86_64") => Ok("apvm-win32-x64-msvc.exe"),
        (os, arch) => Err(Error::Update(format!(
            "No pre-built binary available for {os}/{arch}.\n\
             APVM provides binaries for: macOS (arm64/x64), Linux (x64/arm64), Windows (x64).\n\
             \n\
             To update from source instead:\n\
               cargo install --path crates/cli"
        ))),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Checksum parsing
// ─────────────────────────────────────────────────────────────────────────────

/// Extract the expected SHA-256 hash for a given artifact from `checksums.txt`.
///
/// The checksums file format is the standard `sha256sum` output:
/// ```text
/// <hex_hash>  <filename>
/// ```
///
/// Two spaces separate the hash from the filename (GNU coreutils convention).
/// Source: <https://man7.org/linux/man-pages/man1/sha256sum.1.html>
fn parse_checksum(checksums_text: &str, artifact: &str) -> Result<String> {
    for line in checksums_text.lines() {
        // sha256sum format: "<hash>  <filename>" (two spaces)
        // Also handle single space for robustness.
        let parts: Vec<&str> = line.splitn(2, ' ').collect();
        if parts.len() == 2 {
            let hash = parts[0].trim();
            // Strip a leading `*` produced by `sha256sum -b` (binary mode):
            // text mode:   `<hash>  <filename>`
            // binary mode: `<hash> *<filename>`
            // Source: https://man7.org/linux/man-pages/man1/sha256sum.1.html
            let filename = parts[1].trim().trim_start_matches('*');
            if filename == artifact {
                // Validate hash is 64 hex characters (SHA-256 = 256 bits = 64 hex chars)
                if hash.len() == 64 && hash.chars().all(|c| c.is_ascii_hexdigit()) {
                    return Ok(hash.to_lowercase());
                }
                return Err(Error::Update(format!(
                    "Invalid SHA-256 hash for '{artifact}' in checksums.txt: '{hash}'"
                )));
            }
        }
    }
    Err(Error::Update(format!(
        "No checksum found for '{artifact}' in checksums.txt.\n\
         This may indicate the release assets are incomplete."
    )))
}

// ─────────────────────────────────────────────────────────────────────────────
// Version parsing
// ─────────────────────────────────────────────────────────────────────────────

/// Extract the SemVer version string from a release tag name.
///
/// APVM release tags follow the pattern `cli/vX.Y.Z`. This strips the
/// `cli/v` prefix to get a parseable SemVer string.
///
/// Falls back to stripping just a `v` prefix for compatibility.
fn extract_version_from_tag(tag: &str) -> &str {
    tag.strip_prefix("cli/v")
        .or_else(|| tag.strip_prefix('v'))
        .unwrap_or(tag)
}

// ─────────────────────────────────────────────────────────────────────────────
// Asset lookup
// ─────────────────────────────────────────────────────────────────────────────

/// Find an asset by name within a release's assets list.
fn find_asset<'a>(release: &'a Release, name: &str) -> Result<&'a ReleaseAsset> {
    release
        .assets
        .iter()
        .find(|a| a.name == name)
        .ok_or_else(|| {
            let available = release
                .assets
                .iter()
                .map(|a| a.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            Error::Update(format!(
                "Asset '{name}' not found in release '{}'.\nAvailable assets: {available}",
                release.tag_name
            ))
        })
}

/// Format a byte count as a human-readable string (KB or MB).
fn format_size(bytes: u64) -> String {
    if bytes >= 1_048_576 {
        format!("{:.1} MB", bytes as f64 / 1_048_576.0)
    } else {
        format!("{:.0} KB", bytes as f64 / 1024.0)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// GitHub client construction
// ─────────────────────────────────────────────────────────────────────────────

/// Create a GitHub client for the update check.
///
/// Tries environment variables first (same precedence as the main CLI),
/// falls back to anonymous (rate-limited but sufficient for public repos).
///
/// # Sources
///
/// - `GITHUB_TOKEN` / `GH_TOKEN`: standard environment variables used by
///   GitHub CLI and most CI systems.
///   <https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication>
/// - [`apvm_core::git::resolve_github_token`]: existing token resolution logic.
async fn make_github_client() -> Result<GitHubClient> {
    let resolved = apvm_core::git::resolve_github_token(None).await;
    match resolved {
        Some(rt) => {
            tracing::debug!("Update: using GitHub token from {}", rt.source);
            GitHubClient::new(&rt.token)
        }
        None => {
            tracing::debug!("Update: no GitHub token found, using anonymous client");
            GitHubClient::anonymous()
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/// Execute the update command.
///
/// # Steps
///
/// 1. Fetch the latest release from GitHub
/// 2. Parse and compare versions with `semver`
/// 3. Detect the correct artifact for this platform
/// 4. Download the binary and checksums
/// 5. Verify SHA-256 integrity
/// 6. Atomically replace the running binary via `self-replace`
///
/// # Errors
///
/// Returns `Error::Update` for all update-specific failures (network, checksum
/// mismatch, platform not supported, etc.). Other errors (`Error::GitHub`,
/// `Error::Io`) propagate from underlying operations.
pub async fn execute() -> Result<()> {
    info("Checking for updates...");

    // ── 1. Fetch latest release ──────────────────────────────────────────
    let github = make_github_client().await?;
    let release = github
        .get_latest_release(REPO_OWNER, REPO_NAME)
        .await?
        .ok_or_else(|| {
            Error::Update(format!(
                "No releases found for {REPO_OWNER}/{REPO_NAME}.\n\
                 This is unexpected — please report it at:\n\
                 https://github.com/{REPO_OWNER}/{REPO_NAME}/issues"
            ))
        })?;

    // ── 2. Parse and compare versions ────────────────────────────────────
    //
    // semver::Version::parse():
    //   https://docs.rs/semver/1/semver/struct.Version.html#method.parse
    // semver::Version implements Ord for correct SemVer comparison:
    //   https://docs.rs/semver/1/semver/struct.Version.html#total-ordering
    let current = semver::Version::parse(CURRENT_VERSION).map_err(|e| {
        Error::Update(format!(
            "Failed to parse current version '{CURRENT_VERSION}': {e}"
        ))
    })?;

    let latest_tag = extract_version_from_tag(&release.tag_name);
    let latest = semver::Version::parse(latest_tag).map_err(|e| {
        Error::Update(format!(
            "Failed to parse release version '{}' (from tag '{}'): {e}",
            latest_tag, release.tag_name
        ))
    })?;

    eprintln!();
    success(&format!("Current version: {current}"));
    success(&format!("Latest version:  {latest}"));

    if latest <= current {
        eprintln!();
        success(&format!("apvm {current} is already the latest version."));
        return Ok(());
    }

    // ── 3. Detect platform ───────────────────────────────────────────────
    let artifact = artifact_name()?;
    eprintln!();
    info(&format!("Downloading {artifact}..."));

    // ── 4. Download checksums + binary ───────────────────────────────────
    let checksums_asset = find_asset(&release, CHECKSUMS_FILENAME)?;
    let checksums_bytes = github
        .download_release_asset(REPO_OWNER, REPO_NAME, checksums_asset)
        .await
        .map_err(|e| Error::Update(format!("Failed to download checksums.txt: {e}")))?;
    let checksums_text = String::from_utf8(checksums_bytes)
        .map_err(|e| Error::Update(format!("checksums.txt contains invalid UTF-8: {e}")))?;

    let expected_hash = parse_checksum(&checksums_text, artifact)?;

    let binary_asset = find_asset(&release, artifact)?;
    let binary_bytes = github
        .download_release_asset(REPO_OWNER, REPO_NAME, binary_asset)
        .await
        .map_err(|e| Error::Update(format!("Failed to download {artifact}: {e}")))?;

    success(&format!(
        "Downloaded ({})",
        format_size(binary_bytes.len() as u64)
    ));

    // ── 5. Verify SHA-256 ────────────────────────────────────────────────
    //
    // sha2::Sha256 implements the Digest trait.
    // sha2 0.11 returns an Array newtype; format each byte as two hex digits.
    //   https://docs.rs/sha2/0.11/sha2/type.Sha256.html
    //   https://doc.rust-lang.org/std/fmt/trait.LowerHex.html (u8 impl)
    let hash_bytes = Sha256::digest(&binary_bytes);
    let actual_hash: String = hash_bytes.iter().map(|b| format!("{b:02x}")).collect();

    if actual_hash != expected_hash {
        error_msg("Checksum verification failed!");
        error_msg(&format!("  Expected: {expected_hash}"));
        error_msg(&format!("  Actual:   {actual_hash}"));
        return Err(Error::Update(
            "SHA-256 checksum mismatch — the download may be corrupted.\n\
             Please try again. If the problem persists, report it at:\n\
             https://github.com/wp-media/automation-plugin-version-manager/issues"
                .to_string(),
        ));
    }
    success("Checksum verified (SHA-256)");

    // ── 6. Write to temp file and replace ────────────────────────────────
    //
    // tempfile::NamedTempFile: creates a temporary file that is
    // automatically cleaned up on drop.
    //   https://docs.rs/tempfile/3/tempfile/struct.NamedTempFile.html
    //
    // self_replace::self_replace(): atomically replaces the running binary.
    //   Unix: rename(2) — atomic within the same filesystem.
    //   Windows: rename + FILE_FLAG_DELETE_ON_CLOSE helper process.
    //   https://docs.rs/self-replace/1/self_replace/fn.self_replace.html
    eprintln!();
    info("Updating apvm...");

    let mut temp_file = tempfile::NamedTempFile::new()
        .map_err(|e| Error::Update(format!("Failed to create temporary file: {e}")))?;

    temp_file.write_all(&binary_bytes).map_err(|e| {
        Error::Update(format!(
            "Failed to write downloaded binary to temp file: {e}"
        ))
    })?;

    // Set executable permission on Unix before replacement.
    // std::os::unix::fs::PermissionsExt:
    //   https://doc.rust-lang.org/std/os/unix/fs/trait.PermissionsExt.html
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o755);
        std::fs::set_permissions(temp_file.path(), perms)
            .map_err(|e| Error::Update(format!("Failed to set executable permission: {e}")))?;
    }

    self_replace::self_replace(temp_file.path()).map_err(|e| {
        Error::Update(format!(
            "Failed to replace the binary: {e}\n\
             \n\
             This can happen if:\n\
             - The binary is in a read-only location\n\
             - You don't have write permission to the install directory\n\
             \n\
             Try running with elevated permissions, or download manually from:\n\
             https://github.com/{REPO_OWNER}/{REPO_NAME}/releases/latest"
        ))
    })?;

    success(&format!("Updated successfully: {current} → {latest}"));
    eprintln!();
    info("Restart your shell or run 'apvm --version' to verify.");

    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── artifact_name ────────────────────────────────────────────────────

    #[test]
    fn artifact_name_returns_value_for_current_platform() {
        // This test verifies that the current build target is recognized.
        // It will succeed on any CI or dev machine that matches one of the
        // 5 supported platform/arch combinations.
        let result = artifact_name();
        assert!(
            result.is_ok(),
            "artifact_name() should succeed on supported platforms, got: {:?}",
            result.err()
        );
        let name = result.unwrap();
        assert!(
            name.starts_with("apvm-"),
            "artifact name should start with 'apvm-', got: {name}"
        );
    }

    // ── extract_version_from_tag ─────────────────────────────────────────

    #[test]
    fn extract_version_strips_cli_v_prefix() {
        assert_eq!(extract_version_from_tag("cli/v1.2.3"), "1.2.3");
    }

    #[test]
    fn extract_version_strips_v_prefix() {
        assert_eq!(extract_version_from_tag("v1.2.3"), "1.2.3");
    }

    #[test]
    fn extract_version_handles_bare_version() {
        assert_eq!(extract_version_from_tag("1.2.3"), "1.2.3");
    }

    #[test]
    fn extract_version_preserves_prerelease() {
        assert_eq!(
            extract_version_from_tag("cli/v2.0.0-beta.1"),
            "2.0.0-beta.1"
        );
    }

    // ── parse_checksum ───────────────────────────────────────────────────

    #[test]
    fn parse_checksum_extracts_correct_hash() {
        let checksums = "\
            a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2  apvm-darwin-arm64\n\
            ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff  apvm-linux-x64-gnu\n";
        let hash = parse_checksum(checksums, "apvm-darwin-arm64").unwrap();
        assert_eq!(
            hash,
            "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"
        );
    }

    #[test]
    fn parse_checksum_returns_lowercase() {
        let checksums =
            "ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789  apvm-test\n";
        let hash = parse_checksum(checksums, "apvm-test").unwrap();
        assert_eq!(
            hash,
            "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789"
        );
    }

    #[test]
    fn parse_checksum_errors_on_missing_artifact() {
        let checksums =
            "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2  apvm-other\n";
        let result = parse_checksum(checksums, "apvm-darwin-arm64");
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("No checksum found"),
            "Expected 'No checksum found' error, got: {err}"
        );
    }

    #[test]
    fn parse_checksum_errors_on_invalid_hash_length() {
        let checksums = "tooshort  apvm-darwin-arm64\n";
        let result = parse_checksum(checksums, "apvm-darwin-arm64");
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("Invalid SHA-256 hash"),
            "Expected 'Invalid SHA-256 hash' error, got: {err}"
        );
    }

    #[test]
    fn parse_checksum_errors_on_non_hex_characters() {
        // 64 chars but contains 'g' which is not hex
        let checksums =
            "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg  apvm-darwin-arm64\n";
        let result = parse_checksum(checksums, "apvm-darwin-arm64");
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("Invalid SHA-256 hash"),
            "Expected 'Invalid SHA-256 hash' error, got: {err}"
        );
    }

    #[test]
    fn parse_checksum_handles_empty_input() {
        let result = parse_checksum("", "apvm-darwin-arm64");
        assert!(result.is_err());
    }

    #[test]
    fn parse_checksum_handles_single_space_separator() {
        // Some tools use a single space instead of two
        let checksums =
            "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2 apvm-darwin-arm64\n";
        let hash = parse_checksum(checksums, "apvm-darwin-arm64").unwrap();
        assert_eq!(
            hash,
            "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"
        );
    }

    #[test]
    fn parse_checksum_handles_binary_mode_star_prefix() {
        // `sha256sum -b` produces `<hash> *<filename>` (one space + asterisk).
        // Source: https://man7.org/linux/man-pages/man1/sha256sum.1.html
        let checksums =
            "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2 *apvm-darwin-arm64\n";
        let hash = parse_checksum(checksums, "apvm-darwin-arm64").unwrap();
        assert_eq!(
            hash,
            "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"
        );
    }

    // ── find_asset ───────────────────────────────────────────────────────

    #[test]
    fn find_asset_returns_matching_asset() {
        let release = make_test_release();
        let asset = find_asset(&release, "apvm-darwin-arm64").unwrap();
        assert_eq!(asset.name, "apvm-darwin-arm64");
        assert_eq!(asset.id, 1);
    }

    #[test]
    fn find_asset_errors_on_missing_asset() {
        let release = make_test_release();
        let result = find_asset(&release, "apvm-nonexistent");
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("not found in release"),
            "Expected 'not found in release' error, got: {err}"
        );
        // Should list available assets in the error
        assert!(
            err.contains("apvm-darwin-arm64"),
            "Error should list available assets, got: {err}"
        );
    }

    // ── format_size ──────────────────────────────────────────────────────

    #[test]
    fn format_size_shows_kb_for_small_files() {
        assert_eq!(format_size(512_000), "500 KB");
    }

    #[test]
    fn format_size_shows_mb_for_large_files() {
        assert_eq!(format_size(4_404_019), "4.2 MB");
    }

    // ── version comparison (semver) ──────────────────────────────────────

    #[test]
    fn version_comparison_newer_is_greater() {
        let current = semver::Version::parse("1.2.1").unwrap();
        let latest = semver::Version::parse("1.2.2").unwrap();
        assert!(latest > current);
    }

    #[test]
    fn version_comparison_same_is_equal() {
        let current = semver::Version::parse("1.2.2").unwrap();
        let latest = semver::Version::parse("1.2.2").unwrap();
        assert!(latest <= current);
    }

    #[test]
    fn version_comparison_older_is_less() {
        let current = semver::Version::parse("2.0.0").unwrap();
        let latest = semver::Version::parse("1.9.9").unwrap();
        assert!(latest <= current);
    }

    #[test]
    fn version_comparison_prerelease_is_less_than_release() {
        // Per SemVer spec: 1.0.0-alpha < 1.0.0
        // https://semver.org/#spec-item-11
        let pre = semver::Version::parse("1.2.3-beta.1").unwrap();
        let release = semver::Version::parse("1.2.3").unwrap();
        assert!(pre < release);
    }

    #[test]
    fn version_comparison_major_bump() {
        let current = semver::Version::parse("1.9.9").unwrap();
        let latest = semver::Version::parse("2.0.0").unwrap();
        assert!(latest > current);
    }

    #[test]
    fn current_version_is_valid_semver() {
        // Ensure the compile-time version is always a valid semver string.
        let result = semver::Version::parse(CURRENT_VERSION);
        assert!(
            result.is_ok(),
            "CARGO_PKG_VERSION '{CURRENT_VERSION}' should be valid semver, got: {:?}",
            result.err()
        );
    }

    // ── SHA-256 verification ─────────────────────────────────────────────

    #[test]
    fn sha256_digest_produces_correct_hash() {
        // Known test vector: SHA-256 of empty string
        // Source: https://csrc.nist.gov/projects/cryptographic-standards-and-guidelines
        let hash_bytes = Sha256::digest(b"");
        let hash: String = hash_bytes.iter().map(|b| format!("{b:02x}")).collect();
        assert_eq!(
            hash,
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
    }

    #[test]
    fn sha256_digest_of_known_data() {
        // SHA-256 of "hello" — well-known test vector
        let hash_bytes = Sha256::digest(b"hello");
        let hash: String = hash_bytes.iter().map(|b| format!("{b:02x}")).collect();
        assert_eq!(
            hash,
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
        );
    }

    // ── test helpers ─────────────────────────────────────────────────────

    /// Create a test release with typical assets.
    fn make_test_release() -> Release {
        Release {
            id: 100,
            tag_name: "cli/v1.3.0".to_string(),
            name: "apvm v1.3.0".to_string(),
            prerelease: false,
            draft: false,
            assets: vec![
                ReleaseAsset {
                    id: 1,
                    name: "apvm-darwin-arm64".to_string(),
                    size: 4_404_019,
                    download_url: "https://example.com/apvm-darwin-arm64".to_string(),
                    content_type: "application/octet-stream".to_string(),
                },
                ReleaseAsset {
                    id: 2,
                    name: "apvm-linux-x64-gnu".to_string(),
                    size: 5_200_000,
                    download_url: "https://example.com/apvm-linux-x64-gnu".to_string(),
                    content_type: "application/octet-stream".to_string(),
                },
                ReleaseAsset {
                    id: 3,
                    name: "checksums.txt".to_string(),
                    size: 512,
                    download_url: "https://example.com/checksums.txt".to_string(),
                    content_type: "text/plain".to_string(),
                },
            ],
            html_url: Some("https://github.com/wp-media/automation-plugin-version-manager/releases/tag/cli/v1.3.0".to_string()),
        }
    }
}
